-- post_steps: steps per recipe
CREATE TABLE IF NOT EXISTS public.post_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  sort_order int NOT NULL DEFAULT 0,
  content text NOT NULL,
  image_url text
);

CREATE INDEX IF NOT EXISTS idx_post_steps_post_id_sort ON public.post_steps(post_id, sort_order);
