-- posts: environment setup recipes
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL,
  category_id bigint NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  tags text[] NOT NULL DEFAULT '{}',
  troubleshooting_raw text,
  ai_summary text,
  ai_keywords text[] DEFAULT '{}',
  troubleshooting_notes jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_public boolean NOT NULL DEFAULT true,
  like_count int NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_posts_category_id ON public.posts(category_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON public.posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_title ON public.posts(title);
CREATE INDEX IF NOT EXISTS idx_posts_is_public ON public.posts(is_public);
CREATE INDEX IF NOT EXISTS idx_posts_like_count ON public.posts(like_count DESC);
