-- categories: lookup for recipe category
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  sort_order int NOT NULL DEFAULT 0
);

-- Seed (same order as UI)
INSERT INTO public.categories (name, sort_order) VALUES
  ('Git', 0),
  ('Docker', 1),
  ('ROS', 2),
  ('Kubernetes', 3),
  ('Python', 4)
ON CONFLICT (name) DO NOTHING;
